### ISSUE TITLE
Use . instead of , when numbering.

### ISSUE THREAD

**Issue by tyhdefu** [teedoc/teedoc#10]
In english, we use `.` instead of `.` to number things. e.g:
```
1. A
2. B
3. C
4. D
```
instead of
```
1, A 
2, B
3, C
4, D
```

Is it possible to configure this? Or how would i modify it to do this? Can you point me to the right place.

-----

在英语中，我们使用 `.` 而不是 `.` 进行编号。例如：
```
1. A
2. B
3. C
4. D
```
代替
```
1, A 
2, B
3, C
4, D
```
可以这样配置吗？或者我将如何修改它来做到这一点？你能指出我正确的地方吗？

![image](https://user-images.githubusercontent.com/57567095/156923241-3a8643ba-9dac-402e-a2d3-939614d88044.png)
![image](https://user-images.githubusercontent.com/57567095/156923373-e79a25a5-e44d-485a-b589-a27055e87786.png)

**Comment by Neutree** [comment]
thanks, just need few changes

https://github.com/teedoc/teedoc/blob/d6fe63a68137f467c4b3d4782c4805e4501a85f1/plugins/teedoc-plugin-theme-default/teedoc_plugin_theme_default/assets/main.js#L210-L224
and
https://github.com/teedoc/teedoc/blob/d6fe63a68137f467c4b3d4782c4805e4501a85f1/plugins/teedoc-plugin-theme-default/teedoc_plugin_theme_default/assets/light.css#L535-L544

I'm also considering whether it's appropriate to use roman numerals in the table of contents, or just use numbers

**Comment by tyhdefu** [comment]
Thanks, I have done PR #11 to fix this. It should keep the chinese "、" when the locale is set to `zh`, otherwise it will use the `.`

**Comment by Neutree** [comment]
I optimized code (https://github.com/teedoc/teedoc/commit/4f378d8c05686d6f9fce125dbd4d879f27253f5b) after you PR, now it looks:

Cinese:
![image](https://user-images.githubusercontent.com/8625829/156957996-915a5414-fc23-4a3d-b54f-5811d501a2f2.png)

Others:
![image](https://user-images.githubusercontent.com/8625829/156958126-37435d28-93d8-47a9-9f28-a1a760c8e977.png)

Before:

Chinese:
![image](https://user-images.githubusercontent.com/8625829/156958574-da7bc986-50f4-45b0-b1fa-9172c5412622.png)

Others:
![image](https://user-images.githubusercontent.com/8625829/156958529-76c10e44-b69d-47c4-af44-d917a9ee8dd6.png)

**Comment by Neutree** [comment]
But I remain don't know if roman number should be used like this:

![image](https://user-images.githubusercontent.com/8625829/156959153-106b9ed3-74ea-4913-832c-eceaf18fa43d.png)

**Comment by tyhdefu** [comment]
> But I remain don't know if roman number should be used like this:
> 
> ![image](https://user-images.githubusercontent.com/8625829/156959153-106b9ed3-74ea-4913-832c-eceaf18fa43d.png)

I think its okay, I think it depends on what you prefer
