### ISSUE TITLE
markdown不支持mermaid

### ISSUE THREAD

**Issue by SakurajimaMaii** [teedoc/teedoc#12]
markdown中有以下内容：

```mermaid
graph LR;
VastBaseActivity-->VastVbActivity
VastBaseActivity-->VastVbVmActivity
VastBaseActivity-->VastVmActivity
```

实际预览

![image](https://user-images.githubusercontent.com/46998172/158053647-d37903b1-2e35-4ba4-a210-9160726e424b.png)

**Comment by Neutree** [comment]
已经支持， https://github.com/teedoc/teedoc/commit/963e308ac461632262cf116083852644ad455b3c ， 更新插件即可
```
pip install -U teedoc-plugin-markdown-parser
```

**Comment by Neutree** [comment]
使用方法见: https://teedoc.neucrack.com/get_started/zh/syntax/syntax_markdown.html#mermaid-%E6%94%AF%E6%8C%81

**Comment by SakurajimaMaii** [comment]
感谢感谢
