### ISSUE TITLE
左侧导航栏集成 TOC

### ISSUE THREAD

**Issue by justinliu1985** [teedoc/teedoc#14]
1、右侧toc目录仅能显示3级标题，请问能否实现完整的6级toc导航？

2、能否将toc内容放到左侧sidebar中，通过设置选择左侧sidebar中显示文档toc，还是nav导航菜单？

3、移动端打开时，顶部navbar可否不收缩，保持显示状态？

4、项目模板很好用，文档也很详细，可否donate支持作者？

**Comment by Neutree** [comment]
1： 给主题加了个参数`toc_depth`，现在可以了, 需要`teedoc-plugin-theme-default`插件版本 `>=1.19.1`
更新下插件就好了
```
pip install -U teedoc-plugin-theme-defaul
```

![image](https://user-images.githubusercontent.com/8625829/167148852-eb5a8893-5bb7-4980-a710-4299f310032b.png)

```json
        "teedoc-plugin-theme-default": {
            "from": "pypi",
            "config": {
                "dark": true,
                "show_print_page": true,
                "toc_depth": 6,
                "env": {
                    "main_color": "#4caf7d",
                    "sidebar_width": "300px"
                },
                "code_highlight_css": "/static/css/prism.css",
                "code_highlight_js": "/static/js/prism.js"
            }
        },
```

2. 不支持
3. 可以， 这里查看配置： https://teedoc.neucrack.com/get_started/zh/plugins/themes.html#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE ， `mobile_navbar_collapsed` 设置为`false`即可
4. 可以 感谢  https://neucrack.com/donate

**Comment by justinliu1985** [comment]
非常感谢，已赞赏支持。

**Comment by Neutree** [comment]
@justinliu1985  收到辣！巨资！ 非常感谢！

**Comment by justinliu1985** [comment]
> 
文档写的是真好，我一个完全没有代码基础的人，结合百度和调试工具，上手没有任何障碍。最后提个建议，如果能和docsify一样，不自定义侧边栏的时候，左侧边栏默认显示toc就好了。现在使用移动端或缩小窗口后，右侧边栏无法唤出toc，想要通过左侧侧边栏实现toc只能一条一条手写（不懂勿怪哈），导致移动端没法查看toc。
![image](https://user-images.githubusercontent.com/105055890/167237029-8b805f4f-5fb3-4323-aa52-c4a0f0f96864.png)
![image](https://user-images.githubusercontent.com/105055890/167237053-2f31479e-78ad-42d4-93de-845026d5d2f0.png)
![image](https://user-images.githubusercontent.com/105055890/167237148-7f5e6edc-2bfa-415b-8d28-abf953d50d3b.png)

**Comment by Neutree** [comment]
意思就是和 docsify 一样把TOC集成到左侧导航里面，可以想办法加到左边去

**Comment by justinliu1985** [comment]
> 意思就是和 docsify 一样把TOC集成到左侧导航里面，可以想办法加到左边去

非常期待，试过其他各家平台，要么功能不完善，要么文档看不懂，再次感谢开源这么好的项目并迅速回复！

**Comment by Neutree** [comment]
左侧集成文章目录不太好弄， 给手机也加上了右边的文章目录
![image](https://user-images.githubusercontent.com/8625829/167296529-0f107c79-e22d-48b0-9c7e-cd93dab4f314.png)

**Comment by justinliu1985** [comment]
这样也可以，这个功能如何开启呢

**Comment by justinliu1985** [comment]
> 这样也可以，这个功能如何开启呢

看到那个船锚了，开始没注意，首页显示没问题，但如果滑动到正文中点击按钮，上面导航栏的位置会有块空白，不知能否增加一个选项，设置导航栏始终置顶显示，这样应该就没有空白了，点击搜索按钮也比较方便，现在想要使用搜索，需要先点to top，然后才能在导航菜单中找到搜索按钮
![image](https://user-images.githubusercontent.com/105055890/167297799-352bdf77-4496-41b8-a8cc-44d34609d5ac.png)
![image](https://user-images.githubusercontent.com/105055890/167297847-a33e1058-9d0e-4f8c-b1fa-e75cc20fdd0c.png)

**Comment by justinliu1985** [comment]
又详细测试了下，如果标题只有两级，移动端体验很好，但如果标题超过3级体验就比较一般，可以考虑设置里增加一个选项，允许用户控制是否开启移动端的toc菜单
![image](https://user-images.githubusercontent.com/105055890/167298671-e629a136-5f86-4ee2-8e97-4b1a6ac72743.png)

**Comment by justinliu1985** [comment]
不过导航栏始终显示在顶部的功能还是有需求的，可以节省搜索的操作步骤

**Comment by Neutree** [comment]
目前只能做到这样了，如果想把目录做成和左侧目录体验一样有展开按钮比较麻烦了，我应该暂时不会做了

**Comment by justinliu1985** [comment]
> 目前只能做到这样了，如果想把目录做成和左侧目录体验一样有展开按钮比较麻烦了，我应该暂时不会做了

辛苦辛苦，不知能否设置一个开关，允许移动端不开启toc显示呢

**Comment by justinliu1985** [comment]
还发现一个问题，移动端打开侧栏后，toc的按钮会飘在侧栏上方

**Comment by Neutree** [comment]
toc飘在上方不妥嘛 我感觉好像也还行

**Comment by justinliu1985** [comment]
页面上飘着没啥不妥，但点开左侧侧边栏后，他也飘在上面，感觉有点突兀![image](https://user-images.githubusercontent.com/105055890/167299740-871d2afc-b0ec-4c5c-aabb-a9cf093c8f59.png)

**Comment by Neutree** [comment]
噢确实不太好 我改下

**Comment by Neutree** [comment]
toc图标飘在上面的问题我改好了， 至于搜索框在顶上，在目前的框架上确实不好实现

**Comment by justinliu1985** [comment]
辛苦辛苦，我自己修改了layout和css，最终移动端的效果如下
![image](https://user-images.githubusercontent.com/105055890/167324878-4841d97f-5f53-42c7-a079-fa8e5fa640a3.png)

**Comment by Neutree** [comment]
牛牛

**Comment by justinliu1985** [comment]
还有一个建议哈，移动端唤出侧边栏，点击里面标题的label后，侧边栏不会自动关闭，必须点击左上角的箭头手动关闭，才能查看跳转后的正文，如果能够实现点击label后自动关闭侧边栏就好啦

**Comment by Neutree** [comment]
如果点击的是有超链接的label，会直接访问新的页面，所以不需要关闭
如果点击的是没有超链接的 label，行为和 PC端一样是展开收起目录，也没必要关闭sidebar吧

**Comment by justinliu1985** [comment]
再捉个虫哈，桌面窗口缩小到宽度小于900后，再恢复全屏，左侧sidebar菜单按钮的位置会改变，手动刷新页面可恢复正常。
![image](https://user-images.githubusercontent.com/105055890/167393711-91d6cbe8-9fd9-4747-81c4-e55a97e78c79.png)
![image](https://user-images.githubusercontent.com/105055890/167394559-bd15d1fb-73d8-4f86-ad1d-fc777e63486c.png)

**Comment by justinliu1985** [comment]
解决了，利害

**Comment by justinliu1985** [comment]
更新后的toc菜单移动端很好用，提两个改进建议供参考：

1、可否在设置中，增加调整 tocbot.js “collapseDepth”参数的选项，这样可以直接设置toc菜单默认展开几级目录，我现在是直接到输出后的js文件中手动修改，有点麻烦。

2、如果方便增加前述功能，那么还有一个特性比较实用，即右侧toc跟随滚动，mkdocs的matrial主题（insider版本）支持这个特性，我试用了下确实比较方便，不知加进来会不会很麻烦。
![image](https://user-images.githubusercontent.com/105055890/168483550-4e5876db-3343-4742-91c4-bc143686abf7.png)
