### ISSUE TITLE
窗口缩小至900px以下时正文宽度显示异常

### ISSUE THREAD

**Issue by justinliu1985** [teedoc/teedoc#15]
电脑端手动缩小窗口宽度低于900px时，右侧toc目录自动隐藏，但其占位不会自动消失，导致正文右侧留有一条空白，必须手动刷新页面才能正常显示。![image](https://user-images.githubusercontent.com/105055890/167238044-e48b1a08-39e5-4bea-9e03-d49bda3b6f51.png)
![image](https://user-images.githubusercontent.com/105055890/167238099-c8dc2810-1a90-4a29-b9b1-238bcdcce43f.png)

**Comment by justinliu1985** [comment]
研究了下，win10、edge浏览器，把<div id=article>中的“style="width: calc(78.0778% - 0px);"代码删掉，宽度就正常了，但是不知道怎么改模板
![image](https://user-images.githubusercontent.com/105055890/167296411-514b49e7-1dba-4aab-ada5-83a5561d5e33.png)

**Comment by Neutree** [comment]
已经修复了 https://github.com/teedoc/teedoc/commit/2b285f3530e94c8a4c048f2cd57840bc37f5a5a3 ， 主题插件更新到 `1.19.2`就可以了
```
pip install teedoc-plugin-theme-defaul
```

可以试试

**Comment by justinliu1985** [comment]
> 已经修复了 [2b285f3](https://github.com/teedoc/teedoc/commit/2b285f3530e94c8a4c048f2cd57840bc37f5a5a3) ， 主题插件更新到 `1.19.2`就可以了
> 
> ```
> pip install teedoc-plugin-theme-defaul
> ```
> 
> 可以试试

测试了，完美解决，不过用上面的命令升级会报错，是用teedoc install升级成功的
![image](https://user-images.githubusercontent.com/105055890/167297225-0012049e-8018-42e3-9f1b-2c5e735e9db5.png)

**Comment by Neutree** [comment]
错误是因为你拼写错了 default 不是 defaul

**Comment by justinliu1985** [comment]
> 错误是因为你拼写错了 default 不是 defaul

明白了，我粘贴的时候没仔细瞅
