### ISSUE TITLE
解释器报错UnicodeDecodeError:，添加ignore error可解决

### ISSUE THREAD

**Issue by justinliu1985** [teedoc/teedoc#17]
最早安装的版本运行就会报错，md文档用vscode和notepad++重新转utf-8后依然如此，百度后添加 errors=ignore可正常运行，粗略检查没发现有乱码和缺字，上一个版本更新后好像就正常了，但今天更新后又报相同错误，依然是添加 errors=ignore解决，不知什么原因。![image](https://user-images.githubusercontent.com/105055890/167456317-466a67b4-1f89-4fe3-a9f2-8ed75c9a308c.png)
<img width="579" alt="微信截图_20220510003913" src="https://user-images.githubusercontent.com/105055890/167458383-0c204115-05db-43bc-8993-0f2bb7c9a468.png">

**Comment by justinliu1985** [comment]
不知道啊，我是word文档直接转换的，反正这么设置也没发现啥问题

**Comment by Neutree** [comment]
如果遇到这样的问题，尽量检查下文档内容，首先需要转换为 UTF-8 格式再尝试，如果仍然有错则尝试删掉提示错误的位置，以免有意想不到的bug；
如果不好找错误字符的位置，可以采用二分法删掉一部分内容看有没有出错，直到定位出出错的字符位置，删掉即可。

这个问题先关闭了，如果仍然有疑问欢迎再次打开或者提交新的issue
