### ISSUE TITLE
md文件改名后如何与config.json建立关联

### ISSUE THREAD

**Issue by justinliu1985** [teedoc/teedoc#18]
默认状态下文件夹里的README.md和config.json是自动关联的，我将README.md改名为A1.md后，运行teedoc serve时报错，提示A1.md not have config file!不知应该如何配置

**Comment by Neutree** [comment]
嗯？这是啥奇怪的问题， 不会提示 文件没有config file 的， 你可以把报错截个图

**Comment by justinliu1985** [comment]
1、报错截图
![image](https://user-images.githubusercontent.com/105055890/168719919-b8c0ea30-ebd4-41c6-ba3d-e442d8df094e.png)
2、siteconfig设置
![image](https://user-images.githubusercontent.com/105055890/168720039-1f62195f-ac37-4fd8-98a6-b42a6b436c8b.png)
3、config.json设置
![image](https://user-images.githubusercontent.com/105055890/168720444-c098b2d9-b706-4e03-a5cc-400ce635543f.png)
4、文件夹内容
![image](https://user-images.githubusercontent.com/105055890/168720155-4bf94dd1-f262-4a42-8262-3e766019ca59.png)
5、sidebar设置
![image](https://user-images.githubusercontent.com/105055890/168720280-e106b357-381b-47f2-b193-7c9e412a0e47.png)

**Comment by Neutree** [comment]
你没有理解 route 的用法， route 是用来指定一份文档的路径的，不是用来指定单独的文件路径的

![image](https://user-images.githubusercontent.com/8625829/168720803-5a651f2f-2f67-451c-a904-006e8cc07b18.png)

**Comment by justinliu1985** [comment]
嗯....因为没有基础，这些最基本的常识踩了很多坑，这就要说起我遇到的另一个问题，之前设置的是`route:
    docs:
        /civil_procedure_law/A1-1/: docs/civil_procedure_law/A1-1/`，运行`teedoc serve`没有报错，out文件夹里也生成了A1-1.html，但点击导航栏label访问这个地址`http://127.0.0.1:2333/civil_procedure_law/A1-1/`会报404错误，但把A1-1.html改名为index.html就可以正常访问。所以我就想试着把route指向这个文件看会不会有用

**Comment by justinliu1985** [comment]
直接访问`http://127.0.0.1:2333/civil_procedure_law/A1-1/A1-1.html`可以查看页面，但在侧边栏里设置` -   label: 第一编 总则
        url:  /civil_procedure_law/A1-1/A1-1.html`的话，点击后404，地址栏是这么个地址`http://127.0.0.1:2333/civil_procedure_law/A1-1/no_translate.html?ref=/civil_procedure_law/A1-1/A1-1.html&from=/civil_procedure_law/A1-1//civil_procedure_law/A1-1/A1-1.html`

**Comment by Neutree** [comment]
可以先看看 https://teedoc.neucrack.com/get_started/zh/usage/sites.html 这里这些网站的源码，看看他们怎么写的，参考下

**Comment by justinliu1985** [comment]
我对照了源码，发现创建网页时生成的链接地址多出了`no_translate.html`等内容，然后发现我在文档设置里保留了`locale: zh_CN`，但网站设置里删掉了这个参数。现在我在网站设置里加上了`locale: zh_CN`和文档设置一致，这样问题就解决了。

**Comment by justinliu1985** [comment]
刚又研究了下文档结构，发现确实提了个外行问题，为了避免误导其他人，总结一下阶段性的学习体会：route指向的是网站（书架）中不同文档（书）所在的目录，每个目录（书）下可以包含许多独立的md文件（章节）。teedoc转换的时候，会将这些md文件（章节）输出为同名的html文件，放在out文件夹中该文档（书）对应目录下。需要访问这些html文件（章节）的话，可以在导航和侧边栏设置`URL:.../md文件名.html`。至于config.json和sidebar.yaml，只要md文件所在目录下有这两个文件，就会自动关联，不需要特别设置的话，甚至可以多个md文件使用一套设置文件。
