### ISSUE TITLE
移动端导航栏默认展开

### ISSUE THREAD

**Issue by MeerOst** [teedoc/teedoc#2]
移动端导航栏默认展开，而且刷新以后也是展开的（每篇文章都是这样），但是文档中却没有这个说明，所以不知道是BUG还是什么问题，想请教一下博主，这个怎么解决。如图：https://cdn.jsdelivr.net/gh/MeerOst/MeerOstDrawingBed@master/RaumzeitBlog/202108220158102.png

**Comment by Neutree** [comment]
@MeerOst  是的，暂时没有这个选项可以配置， 但是可以通过在`custom.css`中加一个样式实现：
```
@media screen and (max-width: 900px)
#navbar #navbar_items {
    display: none;
}
```

**Comment by Neutree** [comment]
@MeerOst  好了， 我给默认的主题插件加了配置：
```
"mobile_navbar_collapsed": true,
```
现在默认就会折叠了
文档： https://teedoc.github.io/get_started/zh/plugins/themes.html#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE

**Comment by MeerOst** [comment]
> @MeerOst 好了， 我给默认的主题插件加了配置：
> 
> ```
> "mobile_navbar_collapsed": true,
> ```
> 
> 现在默认就会折叠了
> 文档： https://teedoc.github.io/get_started/zh/plugins/themes.html#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE
> 
> 使用 `teedoc install` 来更新一下主题插件就好了

感谢作者大大
