### ISSUE TITLE
建议增加替换文件功能

### ISSUE THREAD

**Issue by justinliu1985** [teedoc/teedoc#21]
希望teedoc复制md以外的文件到out目录时，支持同名文件自动覆盖。例如，把修改后的light.css，放到static\css\theme_default目录下，运行serve或build后，这个文件可以自动覆盖out\static\css\theme_default里的同名文件，这样便可以达到变相修改主题css的效果（有些全局样式通过新增css一个个改很麻烦，不如在原css中直接删除），这个特性应该还可以用来替换主题默认图标，不知是否合适？

**Comment by Neutree** [comment]
。。。。不需要这样  不是提供了增加 custom.css 的方法吗  

https://github.com/teedoc/teedoc.github.io/blob/2ffb55ce25edfb8f3b5c03bddf01d0b829cd8fb2/site_config.json#L123-L129

https://github.com/teedoc/teedoc.github.io/blob/main/static/css/custom.css

**Comment by Neutree** [comment]
最好的做法就是在 custom.css 覆盖

如果是想改插件的内容，则建议直接修改插件，或者让插件支持相关配置
