### ISSUE TITLE
teedoc serve启动后，后台出现连续规律的HEAD请求

### ISSUE THREAD

**Issue by Luosanmu** [teedoc/teedoc#36]
你好，我发现使用从 https://github.com/teedoc/teedoc.github.io 克隆的仓库到本地，
由teedoc serve运行，
打开http://127.0.0.1:2333/
发现后台不停出现图1的请求，且每个请求dou都如图2的情况，
请问这种情况是否正常，后续我这边需要部署到Nginx上

- 图1
![image](https://github.com/user-attachments/assets/fcef69ac-a0e0-429f-8c10-b96ac37c77f4)

- 图2
![image](https://github.com/user-attachments/assets/231df570-eb2c-4e7d-94db-1c9c850f5ff7)

**Comment by Neutree** [comment]
这是正常的， serve 命令为了实现实时预览，会一直请求更新。

实际部署到 Nginx的不要用 serve 命令生成的文件部署，要用 `teedoc build` 生成的文件部署，在文档里面也有写过说明的。
