### ISSUE TITLE
details标签内的内容不支持markdown

### ISSUE THREAD

**Issue by metaworm** [teedoc/teedoc#4]
想在文档内通过details标签添加一些折叠块，但貌似details标签内的内容不支持markdown，测试代码如下
```markdown
<details><summary>test detail</summary>
* list1
* list2
</details>
```

渲染效果是这样的，没有出现列表
![image](https://user-images.githubusercontent.com/53322237/137665258-e9c6be5e-52a7-44bc-b0cf-b63185a7225d.png)

**Comment by Neutree** [comment]
是的， markdown 解析器（https://github.com/teedoc/teedoc/tree/main/plugins/teedoc-plugin-markdown-parser）暂时还不支持，实际解析用了这个解析库： https://github.com/lepture/mistune

**Comment by Neutree** [comment]
支持了 新的 details 语法
```markdown
.. details::标题，点击展开

    内容一，可以使用 Markdown 语法
    ```kotlin
      fun main() {
          println("Hello World")
      }
    ```

.. details::标题，默认展开
    :open: true

    内容一，可以使用 Markdown 语法
    ```kotlin
      fun main() {
          println("Hello World")
      }
    ```
```

![image](https://user-images.githubusercontent.com/8625829/190837619-05c0ef0c-511c-4729-8259-432e74334288.png)
