### ISSUE TITLE
右侧文章目录，如何配置默认展开？

### ISSUE THREAD

**Issue by metaworm** [teedoc/teedoc#5]
右侧文章目录，如何配置默认展开，文档中没找到相关说明；顺便问下，有没有交流群可以加入

**Comment by Neutree** [comment]
噢不好意思 看错了hhhh 右侧暂时没有设置展开选项 当看到了对应的目录的段落时 会自动展开

**Comment by Neutree** [comment]
https://user-images.githubusercontent.com/8625829/138014401-96f275d7-3e12-434d-9395-18d451e6a7c1.mp4

**Comment by Neutree** [comment]
![qq_group](https://user-images.githubusercontent.com/8625829/138020721-e96d3838-8b0d-4236-a6a2-b72be3f69ea9.png)

建了个qq群
