### ISSUE TITLE
pip3 install teedoc之后还会no module

### ISSUE THREAD

**Issue by Explore-c** [teedoc/teedoc#6]
装了之后还提示no module，是需要再装其他模块吗？
module = __import__(plugin_import_name)
ModuleNotFoundError: No module named 'teedoc_plugin_search'

module = __import__(plugin_import_name)
ModuleNotFoundError: No module named 'teedoc_plugin_theme_default'

module = __import__(plugin_import_name)
ModuleNotFoundError: No module named 'teedoc_plugin_markdown_parser'

**Comment by Neutree** [comment]
需要装插件
到文档的目录下
```
teedoc install
```
