### ISSUE TITLE
summary转换失败，summary内容如下

### ISSUE THREAD

**Issue by Explore-c** [teedoc/teedoc#7]
# 失败
- aa
  - [aa](docs/aa/cc.md)
# 成功
- aa
* [aa](docs/aa/cc.md)
` [aa](docs/aa/cc.md)`前面不能有空格

**Comment by Neutree** [comment]
* 没有支持 `-`号
* 对没有 url 的项目没有处理好

**Comment by Neutree** [comment]
@Explore-c  修改了 https://github.com/teedoc/teedoc/commit/e3da455d2c2d3e36a4d89a63fad66e0480f6026c

更新到 v1.26.3 即可
```
pip3 install -U teedoc
```

**Comment by Neutree** [comment]
issue关闭了，如果仍然有问题，欢迎再打开
