### ISSUE TITLE
如果根目录只保留site_config.yaml而不是json格式，Actions会失败

### ISSUE THREAD

**Issue by SakurajimaMaii** [teedoc/teedoc#9]
我使用指令生成了site_config.json，Action成功了，想问下如何设置只用site_config.yaml就可以

**Comment by Neutree** [comment]
将 json 文件转换成 yaml 格式就好了
```
teedoc -f ./config.json json2yaml
```

文档里也有说 https://teedoc.neucrack.com/get_started/zh/usage/start.html#%E4%BB%8E-json-%E8%BD%AC%E5%88%B0-yaml
